apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ontotools-curation-service
  namespace: ontotools
  labels:
    version: latest
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ontotools-curation-service
    spec:
      containers:
      - name: ontotools-curation-service
        image: "ebispot/ontotools-curation-service:latest-sandbox"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - mountPath: "/var/log/ontotools"
          name: log
        env:
        - name: ENVIRONMENT
          value: "sandbox"
        - name: XMS
          value: "-Xms256m"
        - name: XMX
          value: "-Xms256m"
        - name: LOG_FILE_NAME
          value: "ontotools-curation-service"
        - name: DB_USER
          value: ""
        - name: DB_PASSWORD
          value: ""
      volumes:
      - name: log
        persistentVolumeClaim:
           claimName: ontotools-curation-logs
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: ontotools-curation-service
    version: latest
  name: ontotools-curation-service
  namespace: ontotools
spec:
  type: NodePort
  ports:
  - name: "application"
    port: 8080
  selector:
    app: ontotools-curation-service
