apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ontostring-logs
  namespace: ontotools
spec:
  storageClassName: standard-nfs-production
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
            storage: 5Gi
  
