apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ontotools-curation-logs
  namespace: ontotools
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
            storage: 1Gi
  
