image: docker:latest
services:
  - docker:dind

stages:
  - build-frontend
  - build-artefact
  - build-frontend-release
  - build-artefact-release
  - build-container
  - build-container-release
  - deploy-sandbox
  - deploy-fallback
  - deploy-live

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  REGISTRY_IMAGE: ebispot/ontotools-curation-service
  SERVICE_NAME: ontotools-curation-service

build-front:
  image: node:10.15.3
  stage: build-frontend
  script:
    - npm -v
    - node -v
    - cd frontend
    - rm -rf node_modules
    - npm install
    - CI=false npm run build:sandbox
  artifacts:
    paths:
      - frontend/build/*
  only:
    - develop

maven-build:
  image: maven:3-jdk-12
  stage: build-artefact
  script:
    - mkdir src/main/webapp
    - mv frontend/build/* src/main/webapp/
    - ls -lah src/main/webapp
    - mvn clean package spring-boot:repackage -DskipTests=true
  dependencies:
    - build-front
  artifacts:
    paths:
      - target/*.war
  only:
    - develop

build-container:
  stage: build-container
  script:
    - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
    - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
    - docker build --cache-from $REGISTRY_IMAGE:latest -t $REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - develop
    - tags

build-front-release:
  image: node:10.15.3
  stage: build-frontend-release
  script:
    - npm -v
    - node -v
    - cd frontend
    - rm -rf node_modules
    - npm install
    - CI=false npm run build:prod
  artifacts:
    paths:
      - frontend/build/*
  only:
    - tags

maven-build-release:
  image: maven:3-jdk-12
  stage: build-artefact-release
  script:
    - mkdir src/main/webapp
    - mv frontend/build/* src/main/webapp/
    - ls -lah src/main/webapp
    - mvn clean package spring-boot:repackage -DskipTests=true
  dependencies:
    - build-front-release
  artifacts:
    paths:
      - target/*.war
  only:
    - tags

build-release:
  variables:
    GIT_STRATEGY: none
  stage: build-container-release
  script:
  - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
  - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
  - docker pull $REGISTRY_IMAGE:$CI_COMMIT_SHA
  - docker tag $REGISTRY_IMAGE:$CI_COMMIT_SHA $REGISTRY_IMAGE:latest
  - docker tag $REGISTRY_IMAGE:$CI_COMMIT_SHA $REGISTRY_IMAGE:$CI_COMMIT_TAG
  - docker push $REGISTRY_IMAGE:latest
  - docker push $REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
  - tags

deploy-sandbox:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy-sandbox
  script:
  - echo "Deploy to sandbox server"
  - mkdir -p /root/.kube
  - echo ${SANBOX_KUBECONF} | base64 -d > /root/.kube/config
  - helm init --stable-repo-url https://charts.helm.sh/stable
  - helm delete --purge ontotools-curation-service-sandbox || true
  - helm install --name ontotools-curation-service-sandbox --set k8Namespace=ontotools,image.repository=$REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA,image.env.secretsName=ontotools-secrets,image.env.secretsKey=db-pwd ./k8chart/ --wait
  environment:
    name: sandbox
  only:
  - develop

deploy-fallback:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy-fallback
  script:
  - echo "Deploy to Production fallback server"
  - mkdir -p /root/.kube
  - echo ${PFALLBACK_KUBECONFIG} | base64 -d > /root/.kube/config
  - helm init --stable-repo-url https://charts.helm.sh/stable
  - helm delete --purge ontotools-curation-service || true
  - helm install --name ontotools-curation-service --set k8Namespace=ontotools,replicaCount=1,image.env.envName=fallback,image.repository=$REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA,image.env.dbUser=ontotoolscurator,image.env.secretsName=ontotools-secrets,image.env.secretsKey=db-pwd ./k8chart/ --wait
  environment:
    name: prod
  when: manual
  only:
  - tags

deploy-live:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy-live
  script:
  - echo "Deploy to Production server"
  - mkdir -p /root/.kube
  - echo ${PLIVE_KUBECONFIG} | base64 -d > /root/.kube/config
  - helm init --stable-repo-url https://charts.helm.sh/stable
  - helm delete --purge ontotools-curation-service || true
  - helm install --name ontotools-curation-service --set k8Namespace=ontotools,replicaCount=1,image.env.envName=prod,image.repository=$REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA,image.env.dbUser=ontotoolscurator,image.env.secretsName=ontotools-secrets,image.env.secretsKey=db-pwd ./k8chart/ --wait
  environment:
    name: prod
  when: manual
  only:
  - tags
