server:
  port: 8080

spring:
  config:
    activate:
      on-profile: "sandbox"
  data:
    mongodb:
      uri: mongo-0.mongo.default.svc.cluster.local,mongo-1.mongo.default.svc.cluster.local,mongo-2.mongo.default.svc.cluster.local:27017
