server:
  name: ontotools-curation
  port: 8080

logging:
  level:
    org:
      springframework: DEBUG

ontotools-curation:
  auth:
    enabled: true
    cert: aap.der
  admin:
    robot-user: ontotools-curator@ebi.ac.uk

ontotools:
  zooma:
    base: http://www.ebi.ac.uk/spot/zooma/v2/api
    endpoints:
      annotate: /services/annotate
  oxo:
    base: https://www.ebi.ac.uk/spot/oxo/api/search?size=5000
    mapping-distance: 2
  ols:
    base: https://www.ebi.ac.uk/ols/api
    endpoints:
      ontologies: /ontologies

---

spring:
  config:
    activate:
      on-profile: "dev"
  data:
    mongodb:
      uri: localhost:27017

ontotools-curation:
  db: ontotools-curation-dev

---

spring:
  config:
    activate:
      on-profile: "sandbox"
  data:
    mongodb:
      uri: mongo-0.mongo.default.svc.cluster.local,mongo-1.mongo.default.svc.cluster.local,mongo-2.mongo.default.svc.cluster.local:27017

ontotools-curation:
  db: ontotools-curation-sandbox

---

spring:
  config:
    activate:
      on-profile: "prod"
  data:
    mongodb:
      uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039

ontotools-curation:
  db: ontotools-curation
