apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: ontotools-curation-logs
  namespace: ontotools
spec:
  storageClassName: standard-nfs-production
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

