apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.service.name}}
  namespace: {{.Values.k8Namespace}}
  labels:
    version: {{.Values.image.tag}}
spec:
  replicas: {{.Values.replicaCount}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{.Values.service.name}}
  template:
    metadata:
      labels:
        app: {{.Values.service.name}}
    spec:
      containers:
      - name: {{.Values.service.name}}
        image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
        imagePullPolicy: {{.Values.image.pullPolicy}}
        resources:
          requests:
            cpu: {{.Values.resources.requests.cpu}}
            memory: {{.Values.resources.requests.memory}}
          limits:
            cpu: {{.Values.resources.limits.cpu}}
            memory: {{.Values.resources.limits.memory}}
        ports:
        - name: http
          containerPort: {{.Values.image.containerPort}}
        volumeMounts:
        - mountPath: {{.Values.image.logMountPath}}
          name: log
        env:
        - name: ENVIRONMENT
          value: {{.Values.image.env.envName}}
        - name: XMS
          value: {{.Values.image.env.xms}}
        - name: XMX
          value: {{.Values.image.env.xmx}}
        - name: LOG_FILE_NAME
          value: {{.Values.image.env.logFileName}}
        - name: DB_USER
          value: {{.Values.image.env.dbUser}}
        - name: HTTP_PROXY
          value: http://hh-wwwcache.ebi.ac.uk:3128
        - name: HTTPS_PROXY
          value: http://hh-wwwcache.ebi.ac.uk:3128
        - name: http_proxy
          value: http://hh-wwwcache.ebi.ac.uk:3128
        - name: https_proxy
          value: http://hh-wwwcache.ebi.ac.uk:3128
        - name: no_proxy
          value: localhost,.cluster.local
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Values.image.env.secretsName}}
              key: {{.Values.image.env.secretsKey}}
      volumes:
      - name: log
        persistentVolumeClaim:
           claimName: {{ .Values.image.volume.claimName }}
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{.Values.service.name}}
    version: {{.Values.image.tag}}
  name: {{.Values.service.name}}
  namespace: {{.Values.k8Namespace}}
spec:
  type: {{.Values.service.type}}
  ports:
  - name: "application"
    port: {{.Values.service.port}}
  selector:
    app: {{.Values.service.name}}
