# Default values for ontostring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ebispot/ontostring
  tag: latest
  pullPolicy: Always
  containerPort: 8080
  logMountPath: "/var/log/ontotools"
  env:
    envName: "sandbox"
    logFileName: "ontostring"
    xms: "-Xms256m"
    xmx: "-Xmx256m"
    dbUser: ""
    secretsName: ""
    secretsKey: ""
  volume:
    claimName: ontostring-logs

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  name: ontotools-curation-service
  type: NodePort
  port: 8080

ingress:
  enabled: false

k8Namespace: ontotools

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
