name: Build & publish ontostring images

on:
  push:
    branches: [ "dev", "issue-188" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ontostring Docker image
        run: |
          docker build -t ebispot/ontostring:${{ github.sha }} .
          docker tag ebispot/ontostring:${{ github.sha }} ebispot/ontostring:latest
          docker push --all-tags ebispot/ontostring
